name: build
on: [ pull_request, push ]

jobs:
  build:
    permissions:
      contents: read
      pull-requests: write
    runs-on: ubuntu-26.04
    steps:
      - name: checkout repository
        uses: actions/checkout@v7

      - name: setup jdk
        uses: actions/setup-java@v6
        with:
          java-version: '27'
          distribution: 'oracle'

      - name: setup gradle
        uses: gradle/actions/setup-gradle@9c971963bec38e04b3d30dcc455b5382be2fdbfb
        with:
          cache-encryption-key: ${{ secrets.GRADLE_ENCRYPTION_KEY }}
          add-job-summary-as-pr-comment: 'on-failure'
          allow-snapshot-wrappers: false
          build-scan-publish: true
          build-scan-terms-of-use-url: 'https://gradle.com/terms-of-service'
          build-scan-terms-of-use-agree: 'yes'

      - name: build
        run: ./gradlew build --scan

      - name: capture build artifacts
        uses: actions/upload-artifact@v7
        with:
          archive: false
          path: |
            build/libs/*.jar
            !build/libs/*-dev.jar
            !build/libs/*-sources.jar
            !build/libs/*-javadoc.jar
